# Generated by Django 4.1.2 on 2022-11-01 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sual_text', models.CharField(max_length=200)),
                ('cap_tarixi', models.DateTimeField(verbose_name='cap olundu>>')),
            ],
        ),
        migrations.CreateModel(
            name='Cavab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cavab_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('sual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sorgu.sual')),
            ],
        ),
    ]
